;****************************************************************************
; PollPCM
; Used to update PCM while not idle
;----------------------------------------------------------------------------
; breaks: af
;****************************************************************************

;PollPCM: macro
    macro PollPCM
    ld a, ($4000)
    rrca
    rst $08
    endm

;****************************************************************************
; BankSwitch
; Switches into a new bank (won't update player status!)
;----------------------------------------------------------------------------
; input A .... New bank to switch into
; input HL ... Must be $60xx
;----------------------------------------------------------------------------
; breaks ..... AF
;****************************************************************************

;BankSwitch: macro
    macro BankSwitch
    ld (hl), a
    rrca
    ld (hl), a
    rrca
    ld (hl), a
    rrca
    ld (hl), a
    rrca
    ld (hl), a
    rrca
    ld (hl), a
    rrca
    ld (hl), a
    ld (hl), h
    rrca
    ld (hl), a
    endm
